In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [5]:
b = [1,2,3]
print (b)

[1, 2, 3]


In [8]:
 c= np.array([[1,2,3],[4,5,6,],[7,8,9]])
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
 c= np.array([[1,2,3],[4,5,6,],[7,8,9]])
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.zeros(18)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [14]:
np.ones(18)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [15]:
np.empty(18)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [18]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [19]:
np.arange(0,18,3)

array([ 0,  3,  6,  9, 12, 15])

### add, removed, sort

In [24]:
z = np.append (a, b)
print(z)
z

[1 2 3 1 2 3]


array([1, 2, 3, 1, 2, 3])

In [25]:
np.delete (z, 3)

array([1, 2, 3, 2, 3])

### melihat shape dan size

In [27]:
array3d = np.array ([
    [[1,2],[3,4]],
    [[5,6],[7,9]],
    [[10,11],[12,13]]
])

In [29]:
np.ndim (array3d) #banyak dimensi

3